Repository canonical/anbox-cloud-docs, pull requests merged in 2024-02, with the labels that each got.

#35 Document how to enable support for VirGL
  .wordlist.txt
  explanation/rendering-architecture.md
  howto/anbox/enable-virgl.md
  howto/anbox/landing.md
  index.md
  reference/android-features.md
  reference/supported-rendering-resources.md
Labels: documentation, ready-to-publish

#33 feat(android): document how to use renderdoc with Android
  .wordlist.txt
  howto/android/graphics-debugging-with-renderdoc.md
  howto/android/landing.md
  howto/instance/create.md
  index.md
Labels: ready-to-publish

#21 feat(ref): add VHAL HTTP API documentation
  .wordlist.txt
  reference/anbox-https-api.md
Labels: documentation
